site_name: FIX platform specification
nav:
 - index.md
 - Trading messages:
   - Trading messages/index.md
   - Trading messages/NewOrderSingle.md
   - Trading messages/ExecutionReport.md
   - Trading messages/CancelRequest.md
 - Message components:
   - Message components/StandardHeader.md
   - Message components/RepeatingGroups.md
 - ver.md
theme:
   name: material
   analytics:
     gtag: G-74EPW6P0FB
   palette:
     - scheme: default
       toggle:
         icon: material/brightness-7
         name: Switch to dark
       primary: teal
     - scheme: slate
       toggle:
         icon: material/brightness-4
         name: Switch to light
       primary: teal
   features: 
    - navigation.indexes
    - navigation.expand
markdown_extensions:
 - tables
 - admonition
 - smarty
extra_css:
   - stylesheets/extra.css
extra:
 analytics:
    feedback:
    title: Was this page usefull?
    ratings:
     - icon: material/thumb-up-outline
       name: Yes
       data: 1
       note: Thanks for your feedback!
     - icon: material/thumb-down-outline
       name: No
       data: 0
       note: Sorry, to here it.
